spring.application.name=SpringBootWebServer
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.username=sakshiDB
spring.datasource.password=sakshi123
spring.jpa.hibernate.ddl-auto=create

logging.level.org.springframework.web=DEBUG